version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.0.6

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/lint
      - plugin-ci/test:
          filters:
            tags:
              only: /^v.*/
          requires:
            - plugin-ci/lint
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/lint
            - plugin-ci/build
            - plugin-ci/test
