version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.14

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
      - plugin-ci/build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
          requires:
            - plugin-ci/lint
      - plugin-ci/test:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
          requires:
            - plugin-ci/lint
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
          requires:
            - plugin-ci/lint
            - plugin-ci/build
            - plugin-ci/test
